branches:
  - master
tagFormat: '${version}'
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: angular
      releaseRules:
      # DEFAULT RULES:
      #   type: 'feat' release: 'minor'
      #   type: 'fix' release: 'patch'
      #   type: 'perf' release: 'patch'
        - type: docs
          release: false
        - type: refactor
          release: patch
        - type: test
          release: patch
        - type: style
          release: patch
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - - '@semantic-release/release-notes-generator'
    - preset: angular
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/github'
    - assets:
        - CHANGELOG.md
