---
version: '2.1'

services:
  pihole:
    build: ./pihole
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    environment:
      DNS1: 127.0.0.1#5053
      DNS2: 127.0.0.1#5053
      IPv6: false
      INTERFACE: eth0
      DNSMASQ_LISTENING: eth0
    volumes:
      - pihole_config:/etc/pihole/
      - dnsmasq_config:/etc/dnsmasq.d/
    network_mode: host
  unbound:
    image: klutchell/unbound:armv7hf
    restart: unless-stopped
    ports:
      - 5053:53/tcp
      - 5053:53/udp

volumes:
  pihole_config:
  dnsmasq_config: